/**
 * AFFICHES-EM v1.0 — Marques du catalogue existant
 *
 * Liste extraite de l'export BD-EM-1108.xlsx (2 419 articles), apres
 * normalisation : suppression des extensions de fichier, des accents et des
 * espaces surnumeraires. Trois ecarts de nommage ont ete resolus a la lecture
 * des fichiers de logos disponibles — SAMMSUNG, BEKO LOGO et SEVRIN.
 *
 * Sert uniquement a l'import initial : ensuite, les marques se gerent depuis
 * l'ecran d'administration.
 */

export const MARQUES_CATALOGUE: readonly string[] = [
  'AEG',
  'AIR MONSTER',
  'ALASKA',
  'ANKER',
  'APPLE',
  'ARGO',
  'ARIETE',
  'ARISTON',
  'ARTHUR MARTIN',
  'ARZUM',
  'ASUS',
  'BEKO',
  'BENQ',
  'BOSCH',
  'BRAUN',
  'CANDY',
  'CANON',
  'CHAFFOTEAUX',
  'CITYTEK',
  'DELONGHI',
  'DENWA',
  'DEUTSCHMANN',
  'DYSON',
  'EPSON',
  'FAGOR',
  'FRANKE',
  'HAIER',
  'HISENSE',
  'HONOR',
  'HOOVER',
  'HP',
  'HUAWEI',
  'HYBROK',
  'IMPERIAL',
  'INDESIT',
  'INFINIX',
  'ITEL',
  'ITIMAT',
  'IWA BABY',
  'IWACOOK',
  'JATA',
  'KARCHER',
  'KENWOOD',
  'KRUPS',
  'LENOVO',
  'LG',
  'MEGALIFE',
  'MGS',
  'MONSTER',
  'MOULINEX',
  'OCEAN',
  'OPPO',
  'ORAIMO',
  'OSCAR',
  'RIVACASE',
  'ROWENTA',
  'ROYAL',
  'SAMSUNG',
  'SENCOR',
  'SEVERIN',
  'SEVRIN',
  'SIERA',
  'SOLAC',
  'SONY',
  'STEAMONE',
  'TAURUS',
  'TCL',
  'TEFAL',
  'THOMSON',
  'TOSHIBA',
  'TPLI',
  'TRIOMPHE',
  'UFESA',
  'WHIRLPOOL',
  'XIAOMI',
  'ZANUSSI',
  'ZATEC',
  'ZTE',
] as const;
